baseURL = "https://www.example.com"
languageCode = "zh-cn"
hasCJKLanguage = true
title = "UnityChip Verification"
copyright = "MLVP Group ©"
theme = "hugo-digital-garden-theme"

defaultContentLanguage = 'cn'
defaultContentLanguageInSubdir = false

[params]
  # accesspassword = "123"
  googleAnalytics = "G-4Z2ZY6ZE84"
  baiduAnalytics = "6aacb1c7ca0a3ef4e3aa84c1eaa237dd"

  [[params.social]]
    name = "wechat"
    link = "#"
    icon = "fab fa-weixin"

  [[params.social]]
    name = "weibo"
    link = "#"
    icon = "fab fa-weibo"

[languages]
    [languages.cn]
      disabled = false
      LanguageName = "cn" 
      title = "万众一芯开放验证"

    [languages.cn.params]
      text = "中文"
      initials = "首页"

    [[languages.cn.menu.main]]
      name = "UCagent"
      url = "https://ucagent.open-verify.cc/content/00_index/"
      weight = 1

    [[languages.cn.menu.main]]
      name = "学习资源"
      url = "https://open-verify.cc/mlvp/docs/"
      weight = 2
    [[languages.cn.menu.main]]
      name = "新闻动态"
      url = "/news/"
      weight = 2
    [[languages.cn.menu.main]]
      name = "关于我们"
      url = "https://open-verify.cc/about/"
      weight = 3

    [languages.en]
      disabled = false
      title = "UnityChip Verification"
      languageName = "/en"

    [languages.en.params]
      initials = "Home"
      text = "English"

    [[languages.en.menu.main]]
       identifier = "registration_portal"
       title = "Registration entrance summary"
       name = "Registration entrance summary"
       url = "/en/registration_portal/"
       weight = 1

    [[languages.en.menu.main]]
       identifier = "news"
       title = "News"
       name = "News"
       url = "/en/news/"
       weight = 1

    [[languages.en.menu.main]]
       identifier = "learningresource"
       title = "Learning Resources"
       name = "Learning Resources"
       url = "/en/learningresource/"
       weight = 2

    [[languages.en.menu.main]]
       identifier = "about"
       title = "About Us"
       name = "About Us"
       url = "/en/about/"
       weight = 3

[taxonomies]
  fenbao_tags = 'fenbao_tags'
  resource_tags = 'resource_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
  [markup.tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2
