baseURL = "https://www.example.com"
languageCode = "zh-cn"
title = "Open verification"
copyright = "MLVP Group ©"


[params]
  name = "开源开放芯片验证"
  slog = "会编码就会验证"
  description = "将芯片验证任务拆分成多个子模块，以开源众包的方式分发给所有感兴趣的人，让人们用自己擅长的编程语言进行验证."
  initials = "首页"
  accesspassword = "123"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "#"
    icon = "fab fa-weixin"

  [[params.social]]
    name = "Github"
    link = "#"
    icon = "fab fa-weibo"


[menu]
  [[menu.main]]
    name = "正在进行的验证任务"
    url = "/crowdsourcing/"
    weight = 1
  [[menu.main]]
    name = "学习资源"
    url = "/learningresource/"
    weight = 2
  [[menu.main]]
    name = "关于我们"
    url = "/about/"
    weight = 3


[taxonomies]
  fenbao_tags = 'fenbao_tags'
  resource_tags = 'resource_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
