name: Build Website and Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '55 15 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Set Up timezone
      uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Asia/Shanghai"

    - name: Checkout course
      uses: actions/checkout@v2
      with:
        repository: 'XS-MLVP/course'
        token: ${{ secrets.COMMIT_KEY }}
        path: 'course'

    - name: Checkout doc-xs-ov-00-bpu
      uses: actions/checkout@v2
      with:
        repository: 'XS-MLVP/doc-xs-ov-00-bpu'
        token: ${{ secrets.COMMIT_KEY }}
        path: 'doc-xs-ov-00-bpu'

    - name: Checkout UnityChipForXiangShan
      uses: actions/checkout@v2
      with:
        repository: 'XS-MLVP/UnityChipForXiangShan'
        token: ${{ secrets.COMMIT_KEY }}
        path: 'UnityChipForXiangShan'

    - name: Checkout mlvp-portal
      uses: actions/checkout@v2
      with:
        path: 'mlvp-portal'

    - name: Check if there are commits today
      id: check-commits
      run: |
        skip=true
        for repo in course doc-xs-ov-00-bpu mlvp-portal; do
          cd $repo
          if [ "$(git log --since='1 day ago' --oneline | wc -l)" -ne "0" ]; then
            skip=false
            cd ..
            break
          fi
          cd ..
        done
        cd UnityChipForXiangShan
        LAST_COMMIT=$(git rev-parse HEAD^1)
        DIRECTORY="documents"
        if git diff --quiet $LAST_COMMIT HEAD -- $DIRECTORY; then
          echo "No new commits in $DIRECTORY"
        else
          echo "New commits found in $DIRECTORY"
          skip=false
        fi
        cd ..
        echo "SKIP=$skip" >> $GITHUB_ENV
      shell: bash

    - name: Run make commands
      if: env.SKIP == 'false'
      run: |
        cd /home/runner/work/mlvp-portal/mlvp-portal/course
        make init
        cd /home/runner/work/mlvp-portal/mlvp-portal/doc-xs-ov-00-bpu
        make init
        cd /home/runner/work/mlvp-portal/mlvp-portal/UnityChipForXiangShan
        make init
        cd /home/runner/work/mlvp-portal/mlvp-portal/mlvp-portal 
        npm install -D autoprefixer
        npm install -D postcss-cli
        npm install -D postcss
        make build

    - name: Checkout xs-mlvp.github.io repository
      if: env.SKIP == 'false'
      uses: actions/checkout@v2
      with:
        repository: 'XS-MLVP/xs-mlvp.github.io'
        token: ${{ secrets.COMMIT_KEY }}
        path: 'xs-mlvp.github.io'

    - name: Configure git and sync
      if: env.SKIP == 'false'
      run: |
        cd /home/runner/work/mlvp-portal/mlvp-portal/xs-mlvp.github.io
        git config user.name "github-actions[bot]"
        git config user.email "22570332+github-actions[bot]@users.noreply.github.com"
        make sync
